GITHUB_API_V3_TEST_LOGIN: "username"
GITHUB_API_V3_TEST_PASSWORD: "password"
GITHUB_API_V3_TEST_ACCESS_TOKEN: "7a329f6057f13c496ecf7fd777ceb9e79ae2852d"
GITHUB_API_V3_TEST_CLIENT_ID: "ab0487b031b18f9286a6"
GITHUB_API_V3_TEST_CLIENT_SECRET: "9d667c2b7fae7a329f32b6df179261542ef9229"